VersionChecker.java: Fix error (#64)
java.lang.NullPointerException: Cannot invoke "java.lang.Thread.interrupt()" because "this.thread" is null
when the `enabled: false` parameter is set in `config.yml` in the `update` section, we get this error, no matter how the plugin stops, by the server itself or `plugmanx`